/**
 * ESLint v9 flat config for Next.js 16+
 *
 * This config replaces both .eslintrc.json and the previous FlatCompat-based
 * config that caused circular reference errors with eslint-plugin-react.
 */
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import pluginReact from 'eslint-plugin-react';
import pluginReactHooks from 'eslint-plugin-react-hooks';
import pluginJsxA11y from 'eslint-plugin-jsx-a11y';
import globals from 'globals';
import { dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

export default [
  // Global ignores
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'build/**',
      'public/**',
      'reports/**',
      'tmp/**',
      'temp/**',
      'coverage/**',
      '*.cjs',
      '.prettierrc.cjs',
      'jest.config.cjs',
      'jest.config.esm.cjs',
      'jest.setup.cjs',
      'jest-babel-transformer.cjs',
      'jest-esm-transformer.cjs',
      '__tests__/__testutils__/examples/**',
      'scripts/debug/**',
      'scripts/test-utils/**',
      'scripts/asset-migration/**',
      'scripts/blob-reorganizer/**',
      'scripts/benchmark-downloads.ts',
      'scripts/migrateFullAudiobooks.ts',
      'scripts/migrate*.ts',
      'scripts/test*.ts',
      'scripts/verify*.ts',
      'scripts/audit*.ts',
      'scripts/upload*.ts',
      'utils/ScriptPathUtils.ts',
      'migration-logs/**',
      // Archived migration scripts - not actively maintained
      'archive/**',
      // Next.js autogenerated type files
      'next-env.d.ts',
    ],
  },

  // Base JS recommended
  js.configs.recommended,

  // TypeScript
  ...tseslint.configs.recommended,

  // React
  {
    files: ['**/*.{jsx,tsx}'],
    plugins: {
      react: pluginReact,
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
    rules: {
      ...pluginReact.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
    },
  },

  // React Hooks
  {
    files: ['**/*.{jsx,tsx}'],
    plugins: {
      'react-hooks': pluginReactHooks,
    },
    rules: pluginReactHooks.configs.recommended.rules,
  },

  // Accessibility
  {
    files: ['**/*.{jsx,tsx}'],
    plugins: {
      'jsx-a11y': pluginJsxA11y,
    },
    rules: pluginJsxA11y.configs.recommended.rules,
  },

  // Custom rules
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
    },
  },

  // Test file overrides (Jest and Vitest globals)
  {
    files: [
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.test.js',
      '**/*.spec.ts',
      '**/*.spec.tsx',
      '**/__mocks__/**/*.js',
      '__tests__/**/*.ts',
      '__tests__/**/*.tsx',
      '__tests__/**/*.js',
    ],
    languageOptions: {
      globals: {
        ...globals.jest,
        // Vitest globals
        vi: 'readonly',
        vitest: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      'no-undef': 'off', // Jest/Vitest globals
    },
  },

  // Script file overrides
  {
    files: ['scripts/**/*.ts', 'scripts/**/*.js'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'no-console': 'off',
    },
  },
];
