# Dependabot configuration for Brainrot Publishing House monorepo
version: 2
updates:
  # Root monorepo dependencies (Turborepo, pnpm, etc.)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      # Group all minor and patch updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    reviewers:
      - "phrazzld"

  # Web app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
    open-pull-requests-limit: 5
    groups:
      next-and-react:
        patterns:
          - "next"
          - "react*"
          - "@next/*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "deps(web)"
      include: "scope"
    labels:
      - "dependencies"
      - "web-app"
    reviewers:
      - "phrazzld"

  # Publisher CLI dependencies
  - package-ecosystem: "npm"
    directory: "/apps/publisher"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
    open-pull-requests-limit: 3
    groups:
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright"
    commit-message:
      prefix: "deps(publisher)"
      include: "scope"
    labels:
      - "dependencies"
      - "publisher"
    reviewers:
      - "phrazzld"

  # @brainrot/converter package
  - package-ecosystem: "npm"
    directory: "/packages/@brainrot/converter"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "04:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(converter)"
      include: "scope"
    labels:
      - "dependencies"
      - "packages"
    reviewers:
      - "phrazzld"

  # @brainrot/blob-client package
  - package-ecosystem: "npm"
    directory: "/packages/@brainrot/blob-client"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "04:00"
    open-pull-requests-limit: 3
    groups:
      vercel:
        patterns:
          - "@vercel/*"
    commit-message:
      prefix: "deps(blob-client)"
      include: "scope"
    labels:
      - "dependencies"
      - "packages"
    reviewers:
      - "phrazzld"

  # @brainrot/metadata package
  - package-ecosystem: "npm"
    directory: "/packages/@brainrot/metadata"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "04:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(metadata)"
      include: "scope"
    labels:
      - "dependencies"
      - "packages"
    reviewers:
      - "phrazzld"

  # @brainrot/types package (less frequent as it's mostly interfaces)
  - package-ecosystem: "npm"
    directory: "/packages/@brainrot/types"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "deps(types)"
      include: "scope"
    labels:
      - "dependencies"
      - "packages"
    reviewers:
      - "phrazzld"

  # @brainrot/templates package (less frequent updates)
  - package-ecosystem: "npm"
    directory: "/packages/@brainrot/templates"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "deps(templates)"
      include: "scope"
    labels:
      - "dependencies"
      - "packages"
    reviewers:
      - "phrazzld"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "phrazzld"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "phrazzld"