# GitHub Secret Scanning Configuration
# Custom patterns for Brainrot-specific secrets

paths-ignore:
  - '**/*.md'
  - '.env.example'
  - 'docs/SECRETS.md'
  - '**/*.test.ts'
  - '**/*.test.js'
  - '__tests__/**'

# Custom secret patterns specific to our services
custom-patterns:
  - name: Vercel Blob Token
    pattern: 'vercel_blob_[a-zA-Z0-9]{32,}'
    
  - name: Lulu API Key
    pattern: 'lulu_[a-zA-Z0-9]{20,}'
    
  - name: OpenRouter API Key
    pattern: 'sk-or-[a-zA-Z0-9]{48}'
    
  - name: Anthropic API Key
    pattern: 'sk-ant-[a-zA-Z0-9]{40,}'
    
  - name: Resend API Key
    pattern: 're_[a-zA-Z0-9]{20,}'
    
  - name: Vercel Token
    pattern: '[A-Za-z0-9]{24}'
    paths:
      - '**/vercel.json'
      - '**/.vercel/**'