/**
 * Enhanced mock mode reporter for KDP publishing pipeline
 * Provides comprehensive preview and validation without external dependencies
 */

import * as fs from "fs/promises";
import * as path from "path";
import chalk from "chalk";
import { Logger } from "./logger.js";

export interface MockValidationResult {
  name: string;
  status: "pass" | "fail" | "warning" | "skipped";
  message?: string;
  details?: string;
  timing?: number; // milliseconds
}

export interface MockFileInfo {
  path: string;
  exists: boolean;
  size?: number;
  format?: string;
  lastModified?: string;
  wouldBeGenerated?: boolean;
}

export interface MockPublishingStep {
  step: string;
  description: string;
  status: "pending" | "simulated" | "skipped";
  estimatedDuration?: number; // seconds
  dependencies?: string[];
  mockResults?: any;
}

export interface MockPublishingReport {
  timestamp: string;
  mode: "dry-run" | "mock";
  bookSlug: string;
  platform: string;
  
  // Validation Results
  validations: {
    cover: MockValidationResult[];
    metadata: MockValidationResult[];
    files: MockValidationResult[];
    credentials: MockValidationResult[];
    rateLimits: MockValidationResult[];
  };
  
  // File Analysis
  files: {
    manuscript: MockFileInfo;
    cover: MockFileInfo;
    metadata: MockFileInfo;
    legal: MockFileInfo;
  };
  
  // Publishing Workflow Preview
  workflow: MockPublishingStep[];
  
  // Summary
  summary: {
    totalValidations: number;
    passedValidations: number;
    failedValidations: number;
    warnings: number;
    estimatedPublishTime: number; // seconds
    wouldSucceed: boolean;
    blockers: string[];
    recommendations: string[];
  };
  
  // Mock Results
  mockResults: {
    bookId?: string;
    asin?: string;
    publishUrl?: string;
    status: "would-publish" | "would-draft" | "would-fail";
    estimatedCost?: number;
    marketplaces?: string[];
  };
}

export class MockReporter {
  private report: MockPublishingReport;
  
  constructor(bookSlug: string, platform: string, mode: "dry-run" | "mock" = "dry-run") {
    this.report = {
      timestamp: new Date().toISOString(),
      mode,
      bookSlug,
      platform,
      validations: {
        cover: [],
        metadata: [],
        files: [],
        credentials: [],
        rateLimits: []
      },
      files: {
        manuscript: { path: "", exists: false },
        cover: { path: "", exists: false },
        metadata: { path: "", exists: false },
        legal: { path: "", exists: false }
      },
      workflow: [],
      summary: {
        totalValidations: 0,
        passedValidations: 0,
        failedValidations: 0,
        warnings: 0,
        estimatedPublishTime: 0,
        wouldSucceed: false,
        blockers: [],
        recommendations: []
      },
      mockResults: {
        status: "would-fail"
      }
    };
  }

  /**
   * Add validation result to the report
   */
  addValidation(category: keyof MockPublishingReport['validations'], validation: MockValidationResult): void {
    this.report.validations[category].push(validation);
    this.report.summary.totalValidations++;
    
    switch (validation.status) {
      case "pass":
        this.report.summary.passedValidations++;
        break;
      case "fail":
        this.report.summary.failedValidations++;
        this.report.summary.blockers.push(`${category}: ${validation.message || validation.name}`);
        break;
      case "warning":
        this.report.summary.warnings++;
        break;
    }
  }

  /**
   * Add file information to the report
   */
  async addFileInfo(fileType: keyof MockPublishingReport['files'], filePath: string): Promise<void> {
    const fileInfo: MockFileInfo = {
      path: filePath,
      exists: false,
      wouldBeGenerated: false
    };
    
    try {
      const stats = await fs.stat(filePath);
      fileInfo.exists = true;
      fileInfo.size = stats.size;
      fileInfo.lastModified = stats.mtime.toISOString();
      
      // Detect format from extension
      const ext = path.extname(filePath).toLowerCase();
      switch (ext) {
        case '.epub':
          fileInfo.format = 'EPUB3';
          break;
        case '.jpg':
        case '.jpeg':
          fileInfo.format = 'JPEG';
          break;
        case '.yaml':
        case '.yml':
          fileInfo.format = 'YAML';
          break;
        case '.md':
          fileInfo.format = 'Markdown';
          break;
        default:
          fileInfo.format = ext.substring(1).toUpperCase();
      }
    } catch (error) {
      fileInfo.exists = false;
      
      // Check if this file would be generated by the publishing process
      if (filePath.includes('legal.md') || filePath.includes('validation.json')) {
        fileInfo.wouldBeGenerated = true;
      }
    }
    
    this.report.files[fileType] = fileInfo;
  }

  /**
   * Add workflow step to the report
   */
  addWorkflowStep(step: MockPublishingStep): void {
    this.report.workflow.push(step);
    
    if (step.estimatedDuration) {
      this.report.summary.estimatedPublishTime += step.estimatedDuration;
    }
  }

  /**
   * Generate mock results based on current validation state
   */
  generateMockResults(): void {
    const hasBlockers = this.report.summary.failedValidations > 0;
    const hasWarnings = this.report.summary.warnings > 0;
    
    if (hasBlockers) {
      this.report.mockResults.status = "would-fail";
    } else {
      this.report.mockResults.status = "would-publish";
      this.report.mockResults.bookId = `mock-book-${Date.now()}`;
      this.report.mockResults.asin = `B${Math.random().toString(36).substring(2, 12).toUpperCase()}`;
      this.report.mockResults.publishUrl = `https://www.amazon.com/dp/${this.report.mockResults.asin}`;
      this.report.mockResults.estimatedCost = 0; // KDP is free
      this.report.mockResults.marketplaces = ["US", "UK", "DE", "FR", "ES", "IT", "NL", "JP", "BR", "CA", "MX", "AU", "IN"];
    }
    
    this.report.summary.wouldSucceed = !hasBlockers;
    
    // Add recommendations
    if (hasWarnings) {
      this.report.summary.recommendations.push("Address validation warnings for optimal publishing results");
    }
    
    if (!this.report.files.cover.exists) {
      this.report.summary.recommendations.push("Generate or provide a cover image meeting KDP requirements");
    }
    
    if (!this.report.files.manuscript.exists) {
      this.report.summary.recommendations.push("Run generate:formats to create the EPUB manuscript");
    }
  }

  /**
   * Display comprehensive mock report to console
   */
  displayReport(): void {
    console.log("\n" + "=".repeat(60));
    console.log(chalk.bold.blue(`📋 PUBLISHING PREVIEW REPORT`));
    console.log("=".repeat(60));
    
    // Header
    console.log(chalk.cyan(`📚 Book: ${this.report.bookSlug}`));
    console.log(chalk.cyan(`🏷️  Platform: ${this.report.platform.toUpperCase()}`));
    console.log(chalk.cyan(`⚙️  Mode: ${this.report.mode.toUpperCase()}`));
    console.log(chalk.gray(`🕐 Generated: ${new Date(this.report.timestamp).toLocaleString()}\n`));
    
    // Validation Results
    this.displayValidationResults();
    
    // File Analysis
    this.displayFileAnalysis();
    
    // Workflow Preview
    this.displayWorkflowPreview();
    
    // Mock Results
    this.displayMockResults();
    
    // Summary
    this.displaySummary();
    
    console.log("=".repeat(60) + "\n");
  }

  private displayValidationResults(): void {
    console.log(chalk.bold.blue("🔍 VALIDATION RESULTS"));
    console.log("-".repeat(40));
    
    for (const [category, validations] of Object.entries(this.report.validations)) {
      if (validations.length === 0) continue;
      
      console.log(chalk.bold(`${category.toUpperCase()}:`));
      
      for (const validation of validations) {
        const icon = this.getStatusIcon(validation.status);
        const color = this.getStatusColor(validation.status);
        const timing = validation.timing ? chalk.gray(` (${validation.timing}ms)`) : "";
        
        console.log(chalk[color](`  ${icon} ${validation.name}${timing}`));
        if (validation.message) {
          console.log(chalk.gray(`     ${validation.message}`));
        }
      }
      console.log();
    }
  }

  private displayFileAnalysis(): void {
    console.log(chalk.bold.blue("📁 FILE ANALYSIS"));
    console.log("-".repeat(40));
    
    for (const [fileType, fileInfo] of Object.entries(this.report.files)) {
      const icon = fileInfo.exists ? "✓" : fileInfo.wouldBeGenerated ? "🔄" : "✗";
      const color = fileInfo.exists ? "green" : fileInfo.wouldBeGenerated ? "yellow" : "red";
      const status = fileInfo.exists ? "EXISTS" : fileInfo.wouldBeGenerated ? "WOULD BE GENERATED" : "MISSING";
      
      console.log(chalk[color](`${icon} ${fileType.toUpperCase()}: ${status}`));
      console.log(chalk.gray(`   Path: ${fileInfo.path}`));
      
      if (fileInfo.exists) {
        console.log(chalk.gray(`   Size: ${this.formatFileSize(fileInfo.size || 0)}`));
        if (fileInfo.format) {
          console.log(chalk.gray(`   Format: ${fileInfo.format}`));
        }
      }
      console.log();
    }
  }

  private displayWorkflowPreview(): void {
    if (this.report.workflow.length === 0) return;
    
    console.log(chalk.bold.blue("⚡ WORKFLOW PREVIEW"));
    console.log("-".repeat(40));
    
    for (const step of this.report.workflow) {
      const icon = step.status === "simulated" ? "✓" : step.status === "skipped" ? "⏭" : "⏳";
      const color = step.status === "simulated" ? "green" : step.status === "skipped" ? "gray" : "yellow";
      const duration = step.estimatedDuration ? chalk.gray(` (~${step.estimatedDuration}s)`) : "";
      
      console.log(chalk[color](`${icon} ${step.step}${duration}`));
      console.log(chalk.gray(`   ${step.description}`));
      
      if (step.dependencies && step.dependencies.length > 0) {
        console.log(chalk.gray(`   Depends on: ${step.dependencies.join(", ")}`));
      }
      console.log();
    }
  }

  private displayMockResults(): void {
    console.log(chalk.bold.blue("🎯 MOCK RESULTS"));
    console.log("-".repeat(40));
    
    const statusColor = this.report.mockResults.status === "would-publish" ? "green" : 
                       this.report.mockResults.status === "would-draft" ? "yellow" : "red";
    
    console.log(chalk[statusColor](`Status: ${this.report.mockResults.status.replace("-", " ").toUpperCase()}`));
    
    if (this.report.mockResults.bookId) {
      console.log(chalk.gray(`Mock Book ID: ${this.report.mockResults.bookId}`));
    }
    
    if (this.report.mockResults.asin) {
      console.log(chalk.gray(`Mock ASIN: ${this.report.mockResults.asin}`));
      console.log(chalk.gray(`Mock URL: ${this.report.mockResults.publishUrl}`));
    }
    
    if (this.report.mockResults.marketplaces) {
      console.log(chalk.gray(`Marketplaces: ${this.report.mockResults.marketplaces.length} regions`));
    }
    console.log();
  }

  private displaySummary(): void {
    console.log(chalk.bold.blue("📊 SUMMARY"));
    console.log("-".repeat(40));
    
    // Validation Summary
    const validationColor = this.report.summary.wouldSucceed ? "green" : "red";
    const validationIcon = this.report.summary.wouldSucceed ? "✅" : "❌";
    
    console.log(chalk.bold(`${validationIcon} Overall Status: ${this.report.summary.wouldSucceed ? "READY TO PUBLISH" : "NEEDS ATTENTION"}`));
    console.log(chalk.gray(`Validations: ${this.report.summary.passedValidations}✓ ${this.report.summary.failedValidations}✗ ${this.report.summary.warnings}⚠`));
    
    if (this.report.summary.estimatedPublishTime > 0) {
      console.log(chalk.gray(`Estimated publish time: ${this.formatDuration(this.report.summary.estimatedPublishTime)}`));
    }
    
    // Blockers
    if (this.report.summary.blockers.length > 0) {
      console.log(chalk.red("\nBLOCKERS:"));
      for (const blocker of this.report.summary.blockers) {
        console.log(chalk.red(`  • ${blocker}`));
      }
    }
    
    // Recommendations
    if (this.report.summary.recommendations.length > 0) {
      console.log(chalk.yellow("\nRECOMMENDATIONS:"));
      for (const recommendation of this.report.summary.recommendations) {
        console.log(chalk.yellow(`  • ${recommendation}`));
      }
    }
    console.log();
  }

  private getStatusIcon(status: string): string {
    switch (status) {
      case "pass": return "✓";
      case "fail": return "✗";
      case "warning": return "⚠";
      case "skipped": return "⏭";
      default: return "?";
    }
  }

  private getStatusColor(status: string): "green" | "red" | "yellow" | "gray" {
    switch (status) {
      case "pass": return "green";
      case "fail": return "red";
      case "warning": return "yellow";
      case "skipped": return "gray";
      default: return "gray";
    }
  }

  private formatFileSize(bytes: number): string {
    const units = ["B", "KB", "MB", "GB"];
    let size = bytes;
    let unitIndex = 0;
    
    while (size >= 1024 && unitIndex < units.length - 1) {
      size /= 1024;
      unitIndex++;
    }
    
    return `${size.toFixed(1)} ${units[unitIndex]}`;
  }

  private formatDuration(seconds: number): string {
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    
    if (minutes > 0) {
      return `${minutes}m ${remainingSeconds}s`;
    } else {
      return `${remainingSeconds}s`;
    }
  }

  /**
   * Save report to JSON file
   */
  async saveReport(outputDir?: string): Promise<string> {
    const reportsDir = outputDir || path.join(process.cwd(), "publishing-reports", "mock");
    await fs.mkdir(reportsDir, { recursive: true });
    
    const filename = `${new Date().toISOString().split("T")[0]}-${this.report.bookSlug}-${this.report.platform}-mock-report.json`;
    const reportPath = path.join(reportsDir, filename);
    
    await fs.writeFile(reportPath, JSON.stringify(this.report, null, 2));
    Logger.info(`Mock report saved: ${reportPath}`);
    
    return reportPath;
  }

  /**
   * Get the report object
   */
  getReport(): MockPublishingReport {
    return this.report;
  }
}