name: Sync Translations to DO

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  upload_translations:
    runs-on: ubuntu-latest

    steps:
      - name: check out
        uses: actions/checkout@v3

      - name: set up aws cli
        uses: aws-actions/setup-aws-cli@v2

      - name: configure aws for do spaces
        run: |
          aws configure set aws_access_key_id ${{ secrets.DO_SPACES_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.DO_SPACES_SECRET }}
          aws configure set default.region nyc3
          aws configure set default.s3.signature_version s3v4

      - name: sync translations
        run: |
          echo "syncing translations folder to do spaces..."
          aws s3 sync translations s3://${{ secrets.DO_SPACES_BUCKET }}/translations \
            --endpoint-url https://${{ secrets.DO_SPACES_ENDPOINT }}
